const screenName = {
  Splash: 'Splash',
  Authen: 'Authentication',
  Main: 'Main',
  SignUp: 'Sign Up',
  SignIn: 'Sign In',
  ForgotPass: 'Forgot Password',
  HomeScreen: 'Trang chủ',
  FavoriteScreen: 'Yêu thích',
  BrowseScreen: 'Khám phá',
  SearchScreen: 'Tìm kiếm',
  Search: 'Search Place',
  ListCourses: 'Courses',
  CourseDetails: 'Course Details',
  AllCourses: 'All Courses',
  AuthorProfile: 'Author',
  Browse: 'Browse Home',
  SkillDetails: 'Skill Details',
  CategoryDetails: 'Category Details',
  CategoryListDetails: 'Category List Details',
  ListGroupPaths: 'List Group Paths',
  ListPaths: 'List Paths',
  PathDetails: 'Path Details',
  ProfileScreen: 'ProfileScreen',
  Profile: 'Profile',
};

export default screenName;
