const screenName = {
  Splash: 'Splash',
  Authen: 'Authentication',
  Main: 'Main',
  SignUp: 'Sign Up',
  SignIn: 'Sign In',
  ForgotPass: 'Forgot Password',
  HomeScreen: 'Home',
  FavoriteScreen: 'Favorites',
  BrowseScreen: 'Browse',
  SearchScreen: 'Search',
  ListCourses: 'Courses',
  CourseDetails: 'Course Details',
  AllCourses: 'All Courses',
  AuthorProfile: 'Author',
  Browse: 'Browse Home',
  SkillDetails: 'Skill Details',
  CategoryDetails: 'Category Details',
  CategoryListDetails: 'Category List Details',
  ListGroupPaths: 'List Group Paths',
  ListPaths: 'List Paths',
  PathDetails: 'Path Details',
};

export default screenName;
