export const CHECK_INPUT = 'CHECK_INPUT';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const RESET_REGISTER_STATUS = 'RESET_REGISTER_STATUS';

export const REQUEST_RESET_PASS = 'REQUEST_RESET_PASS';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FAILED = 'RESET_PASS_FAILED';
export const RESET_FORGOT_PASS_STATUS = 'RESET_FORGOT_PASS_STATUS';
