export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const RECEIVE_AUTHOR = 'RECEIVE_AUTHOR';
export const RECEIVE_TOP_NEW = 'RECEIVE_TOP_NEW';
export const REQUEST_FAIL = 'REQUEST_FAIL';

export const RECEIVE_CATEGORY_DETAILS = 'RECEIVE_CATEGORY_DETAILS';
