export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const RECEIVE_CHECK_COURSE = 'RECEIVE_CHECK_COURSE';

export const RECEIVE_LIKE_STATUS = 'RECEIVE_LIKE_STATUS';

export const RECEIVE_COURSE_INFO = 'RECEIVE_COURSE_INFO';

export const RECEIVE_LESSON = 'RECEIVE_LESSON';
export const RECEIVE_PROCESS = 'RECEIVE_PROCESS';

export const LIKE_COURSE_SUCCESS = 'LIKE_COURSE_SUCCESS';
