export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_TOP_NEW = 'RECEIVE_TOP_NEW';
export const RECEIVE_TOP_RATE = 'RECEIVE_TOP_RATE';
export const RECEIVE_TOP_SELL = 'RECEIVE_TOP_SELL';
export const REQUEST_FAILED = 'REQUEST_FAILED';
