export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const REQUEST_FINISH = 'REQUEST_FINISH';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
